### PR TITLE
Implement the delete group API

### PR DESCRIPTION
**Pull request by aaronraimist**

### CODE REVIEW

**Comment by JOJ0** [comment]
Hi thanks a lot for the contribution. I'll try to quickly try it out tonight but from the first looks this can't be wrong and will be merged soon :-) Just being curious: What does the group delete command do? What groups are we talking about? Spaces? Communities? Something else? I think I came across this API while reading docs but couldn't figure out what groups it actually is about. Thanks for shedding some ligth :-)

Also thanks for the readme additions! Great! Very useful!

**Comment by aaronraimist** [comment]
This is deleting what Element calls communities, which were previously called groups. Synapse hasn't really bothered to rename them so they are mostly called groups in Synapse land.

I put the description for `group` as 

> Manage groups (communities)

so hopefully that is clear enough. Otherwise I can add "(communities)" everywhere it says "groups".

Spaces don't exist in Synapse yet.

**Comment by JOJ0** [comment]
Ah alright it's communities. Now that you say it...groups...communities... I think I knew this once haha

Because of naming: Yes I think your suggestion is good. Make it "group (community)" (or plural) everywhere, so no questions and confusions will be left at all. The command name group is actually nice, not only because it reflects what one would find if looking it up in the api docs but also because it's way shorter than community.

Besides that, happy to merge 👍

**Comment by JOJ0** [comment]
you could even add (community) to the link text in the implementation status list

**Pull request merged**
