### PR TITLE
README: Fix typo in user details command

### PR DESCRIPTION
**Pull request by rht**
I have several more issues. More to come.

### CODE REVIEW

**Comment by rht** [comment]
Proof that it is a typo: https://github.com/JOJ0/synadm/blob/df22ea865c02cc89bbac1e634d4416b22d133d45/synadm/cli/user.py#L185

**Comment by JOJ0** [comment]
Hi thanks a lot for the contribution!
Please check back with PR #23 - this typo and some other fixes in the readme are being submitted there!

**Comment by rht** [comment]
Yes, but #23's scope is to implement delete group API, not to fix typos. Typos should be in a separate PR.

**Comment by JOJ0** [comment]
sure, theoretically I am with you, smaller PR's focusing on one thing/fix only are better PR's but let's be not too picky about that. There where some nice additions in there and I want to do a release today and am a bit in a hurry to get things going before going to work :-)

**Pull request closed without merging**
