### PR TITLE
Add scripting examples chapter to docs

### PR DESCRIPTION
**Pull request by JOJ0**

### CODE REVIEW

**Comment by JOJ0** [comment]
image

image

**Comment by JOJ0** [comment]
Enabled the dev branch to show up on readthedocs: https://synadm.readthedocs.io/en/dev/index.html

**Comment by Ascurius** [comment]
Looks good to me. 

However, I wonder if it would be helpful for the users to also provide the scripting examples within the "latest" version branch since I saw that you added some exampled to the dev branch. On the other hand, I am not sure how helpful this would actually be for the users?

**Comment by JOJ0** [comment]
Wirh this merged, latest should have this chapter @Ascurius 

Activating dev on rtd is nice for us to see unmerged docs changes.

**Pull request merged**
