### PR TITLE
json pretty print

### PR DESCRIPTION
**Pull request by waclaw66**

### CODE REVIEW

**Comment by JOJ0** [comment]
please post an example of the difference so I might merge it right away.
afk, cant test
cheers!

**Comment by waclaw66** [comment]
`json.dumps` outputs everything inline, I've added indentation for human reading

original
```json
{"media": [{"media_id": "SFZOcLZamWeKnsnJrfqwfcxr", "media_type": "image/jpeg", "media_length": 344120, "upload_name": "LcV3Ep_YqlJss9A_G8i6", "created_ts": "2022-06-10 16:47:37", "last_access_ts": "2022-11-07 15:01:55", "quarantined_by": null, "safe_from_quarantine": false}, {"media_id": "OgKciuaCYxnBMiiHXXcWqzKP", "media_type": "image/png", "media_length": 786276, "upload_name": "99HFJP4R6Kjvbp9NR0_y", "created_ts": "2022-01-18 17:26:20", "last_access_ts": "2022-04-08 11:04:19", "quarantined_by": null, "safe_from_quarantine": false}], "total": 2}
```

updated
```json
{
    "media": [
        {
            "media_id": "SFZOcLZamWeKnsnJrfqwfcxr",
            "media_type": "image/jpeg",
            "media_length": 344120,
            "upload_name": "LcV3Ep_YqlJss9A_G8i6",
            "created_ts": "2022-06-10 16:47:37",
            "last_access_ts": "2022-11-07 15:01:55",
            "quarantined_by": null,
            "safe_from_quarantine": false
        },
        {
            "media_id": "OgKciuaCYxnBMiiHXXcWqzKP",
            "media_type": "image/png",
            "media_length": 786276,
            "upload_name": "99HFJP4R6Kjvbp9NR0_y",
            "created_ts": "2022-01-18 17:26:20",
            "last_access_ts": "2022-04-08 11:04:19",
            "quarantined_by": null,
            "safe_from_quarantine": false
        }
    ],
    "total": 2
}
```

**Comment by JOJ0** [comment]
Oh, alright that's looking nice but actually we have -o pprint for human readable output. You tried that?

Main question being with your change to json output: Will this still be batch-processable? I.e piping to jq for example? Thats most important usecase for json out.

**Comment by waclaw66** [comment]
> Oh, alright that's looking nice but actually we have -o pprint for human readable output. You tried that?
> 
Yes, it's readable, but it's not json.

> Main question being with your change to json output: Will this still be batch-processable? I.e piping to jq for example? Thats the most important usecase for json out.

Yes, jq works fine, I've tested it.
`synadm media list -u '<user_id>' | jq -c '.media[].media_id'` from previous example returns
```
"SFZOcLZamWeKnsnJrfqwfcxr"
"OgKciuaCYxnBMiiHXXcWqzKP"
```

**Comment by JOJ0** [comment]
I wonder if -o pprint should implement a the pretty-printed-json you suggest here and json should be json in a single string. What do you think?

I am not sure if -o pprint as it's currently implemented has any other purpose to users than just to look nice....

On the other hand, changing it might break existing behaviour in case people have shell scripts that depend on how exactly -o pprint currently looks like for further processing.

Not sure how to proceed. What's your opinion?

**Comment by JOJ0** [comment]
Hi @waclaw66, again: Sorry for the delay and blocking your efforts. I think we have a decision. We'd like to extend this PR to result in the following:

```
Original json mode changes to the pretty version

- `synadm -o json` / `synadm -o j`

and creating one for the oneline/minified version:

- `synadm -o jsonm` / `synadm -o jm`
```

**Comment by JOJ0** [comment]
> * or better add a new universal argument "--pretty" for any output format, that make output format human readible

Also just to be complete here, I'd like to answer to your suggestion: In don't think that's a possible solution since --pretty does not make sense with formats that are already human readable, thus this could be more confusing than helpful. For example: `-o yaml --pretty` or `-o human --pretty` would not really make sense.

**Comment by JOJ0** [comment]
Hi @waclaw66, just want to check in and ask if you still have these requested changes on your radar and whether you plan to submit them? No hurry, since it's not a critical bug fix but a new feature: If you manage to submit during some time in January it's perfectly fine. If you don't find the time until then please give us a heads up. Cheers!

**Comment by JOJ0** [comment]
Some code pointers that might help:

https://github.com/JOJ0/synadm/blob/master/synadm/cli/__init__.py#L346-L354

https://github.com/JOJ0/synadm/blob/master/synadm/cli/__init__.py#L297-L302

**Comment by JOJ0** [comment]
Hi @waclaw66, friendly reminder :-) Will you have time for finishing this PR or would you rather prefer we finish it ourselves. Any answer is ok and just better than no answer at all. Hope you understand! :-) Thanks and all the best!

**Comment by waclaw66** [comment]
Hi @JOJ0, I'm sorry for the late response, please finish it on your own. Currently I'm quite busy. Thanks for understanding.

**Comment by JOJ0** [comment]
> Hi @waclaw66, again: Sorry for the delay and blocking your efforts. I think we have a decision. We'd like to extend this PR to result in the following:
> 
> Original json mode changes to the pretty version
> 
> `synadm -o json` / `synadm -o j`
> 
> and creating one for the oneline/minified version:
> 
> `synadm -o jsonm` / `synadm -o jm`
> 
> After your changes are through I will take the task of improving `synadm --help` to be explicit about what the difference between json and jsonm output modes is. If you feel like it you could include that in this PR but it's certainly not required to finally merge this. I'll take care of that.

I think I'll reconsider here just a little. jsonmini is probably better and even self-descriptive-enough I guess for minified json. The short version jm still is there if we want to spare some typing time: `synadm -o jsonmini` / `synadm -o jm`

**Comment by JOJ0** [comment]
I will finalize this feature in master....soon...

**Pull request merged**
